apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vtorc
  name: vtorc
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    planetscale.com/component: vtorc
  type: ClusterIP
status:
  loadBalancer: {}
